---
# tasks file for jira (Ubuntu specific)

## Failed to validate the SSL certificate for downloads.atlassian.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure.
- name: Trusty | python SNI dependencies
  apt: name={{item}} state=present
  with_items:
    - python-urllib3
    - python-openssl
    - python-pyasn1
  when: ansible_distribution_release == 'trusty'

- name: Trusty | python pip SNI dependencies
  pip: name={{item}} state=present
  with_items:
    - ndg-httpsclient
  when: ansible_distribution_release == 'trusty'

- name: Ensure network tools are present (serverspec testing)
  package:
    name: iproute2
    state: present
  when: jira_testing
