---
prereq_packages:
  - {name: curl, state: latest}
  - {name: policycoreutils-python, state: latest}
  - {name: openssh-server, state: latest}
  - {name: openssh-clients, state: latest}
  - {name: postfix, state: latest}

systemd_vars:
  - {name: sshd, state: started}
  - {name: postfix, state: started}

env_var:
  EXTERNAL_URL: http://centos-gitlab.marthyhome.lab
  
gitlab_url:
  - {url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh, dest: /root/script.rpm.sh}