- name: server_facts
  delegate_to: 127.0.0.1
  os_server_facts:
    auth:
      auth_url: http://192.168.1.100:5000/v2.0/
      username: demo
      password: Pa$$W0rd
      project_name: demo
    server: '{{ ansible_hostname }}'

- set_fact:
    one_fact: "{{ openstack_servers | list }}"

- debug: var=one_fact.metadata