---

prereq_packages:
  - {name: php-cli, state: present}
  - {name: php-common, state: present}
  - {name: php-devel, state: present}
  - {name: php-pear, state: present}
  - {name: php-gd, state: present}
  - {name: php-mbstring, state: present}
  - {name: php-mysql, state: present}
  - {name: php-xml, state: present}
  - {name: "http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm", state: present}
  - {name: policycoreutils-python, state: present}
  - {name: MySQL-python, state: present}
#  - {name: , state: present}


zabbix_packages:
  - {name: zabbix-server-mysql, state: present}
  - {name: zabbix-web-mysql, state: present}