stages:
  - test

test-CentOS:
  image: marthydavid/ansible_lint:centos7
  stages: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

test-Alpine:
  image: marthydavid/ansible_lint:alpine
  stages: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

test-Ubuntu16:
  image: marthydavid/ansible_lint:ubuntu16
  stages: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

test-Debian9:
  image: marthydavid/ansible_lint:debian9
  stages: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check