- hosts: meta-eval_true
  gather_facts: yes
  roles:
    - { role: common} 

- hosts: eval-jira
  gather_facts: yes
  roles:
    - { role: install_jira }

- hosts: eval-bamboo
  gather_facts: yes
  roles:
    - { role: install_bamboo }

- hosts: eval-bitbucket
  gather_facts: yes
  roles:
    - { role: install_bitbucket }