
- hosts: all
  become: yes
  gather_facts: yes
  remote_user: centos
  roles:
    - { role: load_vars}
    - { role: common, when: prereq_tag is defined } 
    - { role: ansible, when: depl_ansible is defined or depl_agent is defined }
    - { role: install_jira, when: depl_jira is defined }
    - { role: install_bamboo, when: depl_bamboo is defined }
    - { role: install_bitbucket, when: depl_bitbucket is defined }
    - { role: install_lamp, when: depl_lamp is defined}
    - { role: install_zabbix, when: depl_zabbix is defined}
    - { role: install_zabbix_agent, when: depl_zabbix_agent is defined}
    - { role: install_docker, when: depl_agent is defined}
    - { role: install_bamboo_agent, when: depl_agent is defined}
    - { role: geerlingguy.gitlab, when: depl_gitlab is defined, gitlab_external_url: "https://centos-gitlab.marthyhome.lab",gitlab_self_signed_cert_subj: "/C=HU/ST=Pest/L=Budapest/O=MARTHYHOME/CN=gitlab",gitlab_time_zone: "UTC"}
