---

- hosts: localhost
  become: no
  roles:
    - { role: create_machines , when: create.isdefined }

- hosts: all
  become: yes
  remote_user: centos
  roles:
    - { role: common, when: prereq_tag.isdefined }

- hosts: centos-ansible
  become: yes
  remote_user: centos
  roles:
    - { role: ansible, when: depl_ansible.isdefined }

- hosts: centos-bamboo
  become: true
  remote_user: centos
  roles:
    - { role: install-bamboo, when: depl_bamboo.isdefined }