---

- hosts: localhost
  become: no
  tags:
    - deploy
  roles:
    - { role: create_machines , when: create is defined }
  tasks:
    - name: refresh inventory
      meta: refresh_inventory

- hosts: localhost
  gather_facts: no
  become: no
  tags:
    - start
  roles:
    - { role: start_machines, when: server_action == "start" or server_action == "stop" and server_action is defined and machinename is defined}

- hosts: all
  become: yes
  gather_facts: no
  tags:
    - prereq
    - ansible-node
  remote_user: centos
  roles:
    - { role: common, when: prereq_tag is defined }

- hosts: all
  become: true
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_docker, when: docker is defined}


- hosts: all
  become: yes
  gather_facts: no
  tags:
    - ansible-node
  remote_user: centos
  roles:
    - { role: ansible, when: depl_ansible is defined }

- hosts: centos-bamboo
  become: yes
  gather_facts: no
  tags:
    - bamboo
  remote_user: centos
  roles:
    - { role: install_bamboo, when: depl_bamboo is defined }

- hosts: centos-jira
  become: yes
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_jira, when: depl_jira is defined }

- hosts: centos-bitbucket
  become: yes
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_bitbucket, when: depl_bitbucket is defined }

- hosts: centos-zabbix
  become: yes
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_lamp, when: depl_lamp is defined}
    - { role: install_zabbix, when: depl_zabbix is defined}

- hosts: all
  become: yes
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_zabbix_agent, when: depl_zabbix_agent is defined}    

- hosts: agent*
  become: true
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_docker, when: depl_agent is defined}

- hosts: agent*
  become: true
  gather_facts: no
  remote_user: centos
  roles:
    - { role: ansible, when: depl_agent is defined}

- hosts: agent*
  become: true
  gather_facts: no
  remote_user: centos
  roles:
    - { role: install_bamboo_agent, when: depl_agent is defined}
  
- hosts: centos-gitlab
  become: true
  remote_user: centos
  roles:
    - {role: geerlingguy.gitlab, when: depl_gitlab is defined, gitlab_external_url: "https://centos-gitlab.marthyhome.lab",gitlab_self_signed_cert_subj: "/C=HU/ST=Pest/L=Budapest/O=MARTHYHOME/CN=gitlab",gitlab_time_zone: "UTC"}
