---

- hosts: localhost
  become: no
  tags:
    - deploy
  roles:
    - { role: create_machines , when: create is defined }
  tasks:
    - name: refresh inventory
      meta: refresh_inventory
- hosts: all
  become: no
  tags:
    - start
  roles:
    - { role: start_machines}

- hosts: all
  become: yes
  remote_user: centos
  roles:
    - { role: common, when: prereq_tag is defined }

- hosts: centos-ansible
  become: yes
  remote_user: centos
  roles:
    - { role: ansible, when: depl_ansible is defined }

- hosts: centos-bamboo
  become: true
  remote_user: centos
  roles:
    - { role: install_bamboo, when: depl_bamboo is defined }

- hosts: centos-jira
  become: true
  remote_user: centos
  roles:
    - { role: install_jira, when: depl_jira is defined }

- hosts: centos-bitbucket
  become: true
  remote_user: centos
  roles:
    - { role: install_bitbucket, when: depl_bitbucket is defined }