---

- hosts: localhost
  become: no
  roles:
    - create_machines

#- hosts: jira
#  become: yes
#  ansible_user: centos
#  ansible_become_method: sudo
#  ansible_become_user: root
#  roles:
#    - { role: kbrebanov.jira }

