---

- name: stat bamboo-agent.service
  stat:
    path: /etc/systemd/system/bamboo-agent.service
  register: service_path
    
- name: create bamboo-agent folder
  file:
    path: /opt/bamboo-agent
    state: directory
    owner: root
    group: root

- name: create bamboo-agent/logs folder
  file:
    path: /opt/bamboo-agent/logs
    state: directory
    owner: root
    group: root

- name: copy the bamboo-agent.jar
  get_url:
    url: 'http://centos-bamboo.marthyhome.lab:8085/agentServer/agentInstaller/atlassian-bamboo-agent-installer-6.2.2.jar'
    dest: /root/atlassian-bamboo-agent-installer-6.2.2.jar
  when: service_path.stat.exists == false

- name: start agent
  command: java -jar -Dbamboo.home=/opt/bamboo-agent /root/atlassian-bamboo-agent-installer-6.2.2.jar http://centos-bamboo.marthyhome.lab:8085/agentServer/ install creates=/opt/bamboo-agent/bin/bamboo-agent.sh
  when: service_path.stat.exists == false

- name: copy bamboo-agent.service
  template:
    src: bamboo-agent.service
    dest: /etc/systemd/system/bamboo-agent.service
    owner: root
    group: root
    mode: 0644
  when: service_path.stat.exists == false

- name: reload systemd
  command: systemctl daemon-reload
  when: service_path.stat.exists == false

- name: start bamboo-agnet
  systemd:
    name: bamboo-agent
    state: started
  when: service_path.stat.exists == false