---
#- include_vars

- name: install prereq packages
  package:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - '{{ prereq_packages }}'

- name: install zabbix packages
  package:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - '{{ zabbix_packages }}'

- name: replace some settings
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - '{{ lineinfile_php }}'
  notify:
    httpd


- name: replace some settings
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    owner: zabbix
    group: zabbix
  with_items:
    - '{{ zabbix_server_conf }}'
  notify:
    - httpd
    - zabbix-server
    - mariadb
