- name: create mysql db for zabbix
  mysql_db:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - '{{ zabbix_mysql_db }}'

- name: create mysql db for zabbix
  mysql_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    priv: '{{ item.priv }}'
    state: '{{ item.state }}'
  with_items:
    - '{{ zabbix_mysql_user }}'
