---
# tasks file for start-machines

- name: starting the machine
  os_server_action:
    action: '{{ server_action }}'
    server: '{{ item.machinename }}'
    wait: yes
  with_items:
    - '{{ machines }}'