---
# tasks file for start-machines

- name: starting the machine
  os_server_action:
    action: '{{ server_action }}'
    server: '{{ item.machinename }}'
    wait: yes
  with_items:
    - '{{ machines }}'

- name: Waiting for machines to get SSH access
  wait_for:
    host: '{{ item.floating_ips }}'
    port: 22
  delegate_to: localhost
  with_items:
    - '{{ machines }}'