---
# tasks file for start-machines

- name: starting the machine
  os_server_action:
    action: '{{ server_action }}'
    server: '{{ machinename }}'
    wait: yes
  with_items:
    - '{{ machines }}'

- name: query machines
  os_server_facts:
    server: '*'

- name: check runnng servers ssh connectivity
  wait_for:
    host: '{{ item.public_v4 }}'
    port: 22
  when: item.vm_state == "active" and item.name == machinename
  with_items:
    - '{{ openstack_servers }}'