---
# tasks file for create_machines
- name: Create the basic machines
  os_server:
    state: '{{ item.state }}'
    name: '{{ item.machinename}}'
    image: '{{ image_id }}'
    key_name: MARTHY-T430
    wait: yes
    flavor: '{{ item.flavor_id }}'
    floating_ips: 
      - '{{ item.floating_ips }}'
    security_groups: default
    nics:
      - net-id: '{{ item.network_id }}'
    meta:
      depl: '{{ item.depl_type }}'
      hostname: '{{ item.hostname}}'
      tag: '{{ item.tag }}'
      state: '{{ item.meta_state }}'
    userdata:
      #cloud-config
      hostname: '{{ item.hostname }}'
  with_items:
    - '{{ machines }}'

- name: query machines
  os_server_facts:
    server: '*'

- name: check runnng servers ssh connectivity
  wait_for:
    host: '{{ item.public_v4 }}'
    port: 22
  when: item.vm_state == "active"
  with_items:
    - '{{ openstack_servers }}'
