---
# tasks file for create_machines
- name: Create the basic machines
  os_server:
    state: '{{ item.state }}'
    name: '{{ item.machinename}}'
    image: '{{ image_id }}'
    key_name: MARTHY-T430
    wait: yes
    flavor: '{{ item.flavor_id }}'
    floating_ips: 
      - '{{ item.floating_ips }}'
    security_groups: default
    nics:
      - net-id: '{{ item.network_id }}'
    meta:
      hostname: '{{ item.hostname}}'
      tag: "{{ item.tag }}"
    userdata:
      #cloud-config
      hostname: '{{ item.hostname }}'
  with_items:
    - '{{ machines }}'
