---
# tasks file for create_machines

- name: Create the basic machines
  os_server:
    state: present
    name: '{{ item.machinename}}'
    image: '{{ image_id }}'
    key_name: MARTHY-T430-WIN
    timeout: 200
    flavor: '{{ item.flavor_id }}'
    floating_ips: 
      - '{{ item.floating_ips }}'
    security_groups: default
    boot_from_volume: True
    volume_size: 20
    nics:
      - net-id: '{{ network_id }}'
    meta:
      hostname: "{{ item.hostname}}"
  with_items:
    - '{{ machines }}'
