---
# defaults file this project
infra_1g: f024e0ba-7cdf-4a38-9b4d-0472d13b2308
infra_2g: 7c634b6f-d7e4-44f1-b5bd-930a04b6d5a7
infra_3g: 2076a802-712e-4ba6-85e3-ac8cb5216f74
m1_large: '4'
centos_image_id: 1fda8fed-66ca-42d0-b671-f01b066b9f79
windows_image_id: 8742f0ec-ff17-4b58-b95f-51a790419b41
ubuntu_image_id: 0d42ae71-ec3b-483b-a77d-c2489dd2804f
network_id_private: 385b0956-d037-4cfd-845b-6047e9bac790
jira_link: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.5.2-x64.bin
bamboo_link: https://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-6.2.2.tar.gz
bitbucket_link: https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.5.0-x64.bin
prereq_packages:
  - { name: epel-release, state: present}
  - { name: "https://centos7.iuscommunity.org/ius-release.rpm", state: present}
  - { name: git2u, state: present}
  - { name: python-devel, state: present}
  - { name: vim, state: present}
  - { name: java-1.8.0-openjdk, state: present}
cloud_init_user_name: marth
cloud_init_user_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDY/e1KJUiwOWUNr9RJb7DrUJqEH/8z1bvAW1XvzkNem697mDuqaZTq9D6TbVQf/NLJjSWiHlw7vhyzw+xSUExC0BDwv7CzPvRzgzpvF+AGNda7FhOElUprglxFeg08urxNOtSIzzsyBQcSyay2TfGb8Bho9/w3E88HB0UoRuUbNV8l1cXMUmkfH4WJgqzhZiJyPGzxfqtQ0gxf4MvqGbehzFtTIhlwf5Mqh/UYga7UwPgj/t/q+pKXMH4wNyAAzL0qWe5WCh99aNPyXR8DFGbg93pSdIQzNHpuyI4TS9NSOGcl+WrLFYEy8UTRIr6g7oFXJKN1EXdLFlAMC9xCB/Yp"