- name: Template out heatfile
  local_action: true
  template:
    dest: heat.yml 
    src: heat.yml 
    
#- name: Start up with heat
#  os_stack:
#    name: undefined # required. Name of the stack that should be created, name could be char and digit, no space
#    template: None # not required. Path of the template file to use for the stack creation
#    wait: yes # not required. choices: yes;no. Should ansible wait until the requested resource is complete.