- name: attach volume to host
  os_server_volume:
    state: '{{ item.disk_state }}'
    server: '{{ item.machinename}}'
    volume: '{{ item.disk_name}}'
    device: '{{ item.disk_device }}'
  when: item.disk_name is defined
  with_items:
    - '{{ machines }}'