---
- name: query pip
  stat:
    path: /usr/bin/pip
  register: pip

- name: install pip
  command: easy_install pip
  when: pip.stat.exists == False


- name: install yum packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state}}'
  with_items:
    - '{{ packages }}'

- name: query shade
  stat:
    path: /usr/lib/python2.7/site-packages/shade
  register: shade

- name: install shade with pip
  pip:
    name: '{{ item.name }}'
  with_items:
    - '{{ pip_packages }}'
  when: pip.stat.exists and shade.stat.exists == False

- name: stat maven dir
  stat:
    path: /opt/apache/maven
  register: maven

- name: create maven dir
  file:
    state: directory
    owner: root
    group: root
    mode: 0777
    path: /opt/apache/maven
    force: yes
  when: maven.stat.exists == False
  register: maven_created

- name: install maven
  get_url:
    url: https://www.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
    dest: /home/centos/apache-maven.bin.tar.gz
    mode: 0755

- name: unpack
  unarchive:
    src: /home/centos/apache-maven.bin.tar.gz
    dest: /opt/apache/maven
    remote_src: yes
    owner: root
    group: root
    copy: no
    mode: 0755
  when: maven_created.changed

- name: create link for bin
  file:
    state: link
    src: /opt/apache/maven/bin/mvn
    dest: /usr/bin/mvn
    mode: 0777

- name: copy profile.d/maven.sh
  template:
    src: maven.sh
    dest: /etc/profile.d/maven.sh
    owner: root
    group: root
    mode: 0777
