---
- name: query pip
  stat:
    path: /usr/bin/pip
  register: pip

#- name: install pip
#  command: easy_install pip
#  when: pip.stat.exists == False


- name: install yum packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state}}'
    
  with_items:
    - '{{ packages }}'

- name: query shade
  stat:
    path: /usr/lib/python2.7/site-packages/shade
  register: shade

- name: install shade with pip
  pip:
    name: '{{ item.name }}'
  with_items:
    - '{{ pip_packages }}'
  when: pip.stat.exists and shade.stat.exists == False

- name: get repo
  get_url:
    url: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
    dest: /etc/yum.repos.d/epel-apache-maven.repo
    owner: root
    group: root
    mode: 644

- name: install maven
  yum:
    name: apache-maven
    state: present
    
