---

- name: install packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - '{{ yum_packages }}'

- name: copy php_info
  template:
    src: info.php
    dest: /var/www/html/info.php
    mode: 0644
    owner: root
    group: root 

- name: start services
  systemd:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    enabled: '{{ item.enabled }}'
  with_items:
    - '{{ systemd_apps }}'
