---
yum_packages:
  - {name: httpd, state: present}
  - {name: mariadb, state: present}
  - {name: mariadb-server, state: present}
  - {name: php, state: present}
  - {name: php-mysql, state: present}

systemd_apps:
  - {name: httpd, state: started, enabled: true}
  - {name: mariadb, state: started, enabled: true}
  - {name: httpd, state: restarted, enabled: true}