---

zabbix_agent_package:
  - {name: "http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm", state: present}
  - {name: zabbix-agent, state: present}


linein_agentd:
  - {path: /etc/zabbix/zabbix_agentd.conf, regexp: ^Server=, line: Server=192.168.1.206}
  - {path: /etc/zabbix/zabbix_agentd.conf, regexp: ^Hostname=, line: Hostname={{ ansible_hostname }}}